name: manga_easy_downloads
description: Micro app de downloads do manga easy.
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  manga_easy_sdk:
    path: ../manga_easy_sdk

  coffee_cup:
    path: ../manga_easy_coffee_cup
  hosts:
    path: ../lib_hosts
  # client_driver:
  #   git:
  #     url: https://github.com/manga-easy/manga_easy_client_driver.git
  #     ref: v1.1.1
  manga_easy_themes:
    git:
      url: https://github.com/manga-easy/manga_easy_themes.git
      ref: 1.0.2
  manga_easy_routes:
    git:
      url: https://github.com/manga-easy/manga_easy_routes.git
      ref: v1.0.2
  persistent_database:
    path: ../lib_persistent_database
  # manga_easy_hosts:
  #   git:
  #     url: https://github.com/manga-easy/manga_easy_hosts.git
  #     ref: v1.0.5
  
  get_it: ^7.2.0
  reorderables: ^0.6.0
  file_picker: ^5.3.2
  flutter_image_compress: ^2.0.3
  dio: ^5.2.1+1
  permission_handler: ^10.3.0
dependency_overrides: 
  manga_easy_sdk:
    path: ../manga_easy_sdk
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: 0.4.0
  manga_easy_lint_rules:
    git:
      url: https://github.com/manga-easy/manga_easy_lint_rules.git
      ref: v1.0.1

flutter:
